Add cobol textmate language and configuration.
barrettotte/vscode-ibmi-languages pull request #129
Opened 2023-06-06 14:38 UTC by kathma0905

2023-06-06 17:09 UTC, worksofliam requested changes
Please see my comments

2023-06-06 17:09 UTC, worksofliam commented on package.json
> +					".srvpgm.sqlcblle"
`.srvpgm` not required here.

2023-06-06 17:09 UTC, worksofliam commented on configurations/cobol.language-configuration.json
> +/*******************************************************************************
Can't have comments like this in JSON.

2023-06-06 19:48 UTC, chrjorgensen requested changes
@kathma0905 Nice addition to the IBM i languages! 👍 

Please provide some COBOL sources in the `test/general` directory to show your grammar in action when debugging this extension - like the other source examples. The COBOL sources should ideally cover all aspects (keywords, operation codes, identifiers etc) of COBOL to validate the grammar.

2026-07-26 07:16 UTC, barrettotte commented
Going to revive this as part of my repo refresh and base it on this syntax and IBM docs. Also going to add samples/tests following the new test pattern

2026-07-29 04:48 UTC, barrettotte commented
Wrote IBM i specific COBOL (probably limited due to my lack of experience and using IBM i docs) in https://github.com/barrettotte/vscode-ibmi-languages/pull/193

2026-07-29 04:48 UTC, closed without merging